#
# Ref:
#   https://docs.docker.com/compose/compose-file
#

version: "3.7"

services:
  user:
    build:
      context: .
    container_name: user
    restart: always
    volumes:
      - .:/user
    ports:
      - 8082:8082
    depends_on:
      - postgres
    environment:
      - PORT=8082
    command: make docker-compose-init
  postgres:
    image: postgres:12.1
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
