#
# Ref:
#   https://docs.docker.com/compose/compose-file
#

version: "3.7"

services:
  postgres:
    image: postgres:12.1
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
